#== Fizz Buzz Code Challenge
#
# Write a program that prints out the pattern generated by playing
# a variation of the Fizz Buzz game where we'll count from 1 to 100
# replacing any number divisible by four with `Fizz`, any number
# divisible by six with `Buzz`, any number divisible by either four or six
# with `Fizz Buzz`, and any number divisible by the product of `4 x 6` with
# `Fizz Buzz BOOM`.

start_time = Time.now

(1..100).to_a.each do |n|
  case true
  when n % 24 == 0 then puts 'Fizz Buzz BOOM'
  when n % 12 == 0 then puts 'Fizz Buzz'
  when n % 6 == 0 then puts 'Buzz'
  when n % 4 == 0 then puts 'Fizz'
  else puts n
  end
end

puts "\nCompleted in #{Time.now - start_time} ms"
