<?php

/**
 * Fizz Buzz Code Challenge
 *
 * Write a program that prints out the pattern generated by playing 
 * a variation of the Fizz Buzz game where we'll count from 1 to 100 
 * replacing any number divisible by four with `Fizz`, any number 
 * divisible by six with `Buzz`, any number divisible by either four or six 
 * with `Fizz Buzz`, and any number divisible by the product of `4 x 6` with 
 * `Fizz Buzz BOOM`.
 */




?>