<?php

/**
 * Fizz Buzz Code Challenge
 *
 * Write a program that prints out the pattern generated by playing 
 * a variation of the Fizz Buzz game where we'll count from 1 to 100 
 * replacing any number divisible by four with `Fizz`, any number 
 * divisible by six with `Buzz`, any number divisible by both four and six 
 * with `Fizz Buzz`, and any number divisible by the product of `4 x 6` with 
 * `Fizz Buzz BOOM`.
 */

$start = microtime();

foreach(range(1, 100) as $n) {
	switch (true) {
		case($n % 24 == 0):
			echo "Fizz Buzz BOOM\n";
			break;
		case($n % 4 == 0 && $n % 6 == 0):
			echo "Fizz Buzz\n";
			break;
		case($n % 6 == 0):
			echo "Buzz\n";
			break;
		case($n % 4 == 0):
			echo "Fizz\n";
			break;
		default:
			echo "$n\n";
			break;
	}
}

$end = microtime();
$time = $end - $start;

echo "\nCompleted in " . $time . " ms";



?>