<?php

/**
 * Fizz Buzz Code Challenge
 *
 * Write a program that prints out the pattern generated by playing 
 * a variation of the Fizz Buzz game where we'll count from 1 to 100 
 * replacing any number divisible by four with `Fizz`, any number 
 * divisible by six with `Buzz`, any number divisible by either four or six 
 * with `Fizz Buzz`, and any number divisible by the product of `4 x 6` with 
 * `Fizz Buzz BOOM`.
 */

$results = array();

for ($i = 1; $i <= 100; $i++) {
  $result = '';
  if ($i % 4 == 0) $result = 'Fizz';
  if ($i % 6 == 0) $result .= ' Buzz';
  if ($i % (4 * 6) == 0) $result .= ' BOOM';
  if (empty($result)) $result = $i;
  $results[] = trim($result);
}

echo implode(', ', $results) . "\n";

?>